import { Request, Response } from 'express';
const { setCorsHeaders } = require('./_utils/cors');

module.exports = {
  name: 'ts-demo',
  desc: 'ts apis',
  apis: [
    {
      name: 'ts-demo lov options',
      desc: 'CORS preflight',
      method: 'OPTIONS',
      url: '/demo/lov',
      handle: (req: Request, res: Response) => {
        setCorsHeaders(req, res);
        res.sendStatus(200);
      },
    },
    {
      name: 'ts-demo one',
      desc: 'example',
      method: 'GET',
      url: '/demo/lov',
      handle: (req: Request, res: Response) => {
        setCorsHeaders(req, res);
        res.status(200);
        res.send({
          "totalPages": 2,
          "totalElements": 18,
          "numberOfElements": 10,
          "size": 10,
          "number": 0,
          "content": [
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB+0cVYePs0FAW2eRJJWIPuc=",
              "tenantId": "6",
              "supplierId": "754020897190981641",
              "supplierCode": "797885",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "麦丰（佛山）药业有限公司",
              "supplierShortName": "麦丰",
              "unifiedSocialCode": "91440604MADFC9K28N",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZYbrQuozxKXGhk9Nw3axJwuKohzj4Uy8aXmDRQy0mLPQ=",
              "tenantId": "6",
              "supplierId": "759005108890865670",
              "supplierCode": "100073",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "广东蜂窝工场电子科技有限公司",
              "supplierShortName": "蜂窝",
              "unifiedSocialCode": "91441900MA52XAX641",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB87reT/nwbpGsRNLrkO624o=",
              "tenantId": "6",
              "supplierId": "754020897190981648",
              "supplierCode": "785758",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳市椰子生物科技有限公司",
              "supplierShortName": "椰子",
              "unifiedSocialCode": "91440300MA5GDKGM81",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB7b6PBo1zqmh5bBcYlZfAl8=",
              "tenantId": "6",
              "supplierId": "754020897190981647",
              "supplierCode": "754421",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳市真味生物科技有限公司",
              "supplierShortName": "真味",
              "unifiedSocialCode": "91440300359914415M",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB+hkIKo9WDlMqeuLaJtI3vU=",
              "tenantId": "6",
              "supplierId": "754020897190981646",
              "supplierCode": "622246",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳云普星河科技服务有限公司",
              "supplierShortName": "云普",
              "unifiedSocialCode": "91440300MA5GPJGM0E",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB+7AdSWrhXf0J8Z3+BzxS5E=",
              "tenantId": "6",
              "supplierId": "754020897190981645",
              "supplierCode": "765505",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳易佳特科技有限公司",
              "supplierShortName": "易佳特",
              "unifiedSocialCode": "91440300557198288B",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB30LDabi669LFZzpdJ3cMkA=",
              "tenantId": "6",
              "supplierId": "754020897190981644",
              "supplierCode": "22328",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳市热火科技有限公司",
              "supplierShortName": "热火",
              "unifiedSocialCode": "914403000769478586",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB9xQrWYrRC6xS0iKTsgYCWM=",
              "tenantId": "6",
              "supplierId": "754020897190981643",
              "supplierCode": "533508",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳市禾晗科技有限公司",
              "supplierShortName": "禾晗",
              "unifiedSocialCode": "91440300MA5GL5YH41",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB1kgG8MAyO27Tm6l6DZtpME=",
              "tenantId": "6",
              "supplierId": "754020897190981642",
              "supplierCode": "21493",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "深圳东灏兴科技有限公司",
              "supplierShortName": "东灏兴",
              "unifiedSocialCode": "91440300568546997E",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            },
            {
              "creationDate": "2025-09-25 10:55:20",
              "createdBy": 1,
              "lastUpdateDate": "2025-09-25 10:55:20",
              "lastUpdatedBy": 1,
              "objectVersionNumber": 1,
              "_token": "sC9iSordwYtLKByXkl+NYm6saTILMKWlChN8/9qPn33RZyuAyPrCfYUEWIVlSAfZi8g8qyR/6hBkj9n3y0kuB6+/SRs0yDVrhEMTOxwDrdA=",
              "tenantId": "6",
              "supplierId": "754020897190981639",
              "supplierCode": "100013",
              "supplierType": "BK01",
              "supplierLevel": "代工厂,一级供应商",
              "supplierName": "东莞市鸿馥生物科技有限公司",
              "supplierShortName": "鸿馥",
              "unifiedSocialCode": "91441900MA51BPAP3K",
              "enabledFlag": 1,
              "supplierTypeMeaning": "生产",
              "enabledFlagMeaning": "是",
              "createdByName": "匿名用户",
              "lastUpdatedByName": "匿名用户"
            }
          ],
          "empty": false
        });
      },
    }
  ]


};
