import { FieldComponentType } from 'hzero-front-apaas/lib/constants/businessObject';
export declare function polyfillData(res: any): void;
export declare const viewTypeApi: (apiModelRecord: any, apiType: any) => boolean;
export declare const handleAttributeJson: (body: any, isExtensionField: boolean) => any;
export declare const handleFieldChange: ({ ds, value, businessObjectId, oType }: {
    ds: any;
    value: any;
    businessObjectId: any;
    oType: any;
}) => void;
export declare const hasMaxLengthFieldList: FieldComponentType[];
export declare const setDefaultMaxLength: (record: any, value: any) => void;
export declare const handleFieldSave: ({ formValues, componentType, childrenComRef, getInheritType, businessObjectCode, isExtensionField, businessObjectId, isApiCustomType, selectComponentName, apiModelRecord, apiType, handleCloseDetail, getAddonBefore, fastCreateEnter, businessObjectFieldId, fastCreateEnterRecord, fieldType, boSourceType, createPlateformExtensionBusinessObjectField, oldComponentType, isEditMode, modal, domainId, updateBusinessObjectField, createBusinessObjectField, isFromDomain, dominFieldExtendsDs, templateCode, editDomainTemplateField, createDomainTemplateField, updatePlateformExtensionBusinessObjectField, createTenantExtensionBusinessObjectField, handleDeleteCheckApi, dispatchService, type, }: {
    formValues: any;
    componentType: any;
    childrenComRef: any;
    getInheritType: any;
    businessObjectCode: any;
    isExtensionField: any;
    businessObjectId: any;
    isApiCustomType: any;
    selectComponentName: any;
    apiModelRecord: any;
    apiType: any;
    handleCloseDetail: any;
    getAddonBefore: any;
    fastCreateEnter: any;
    businessObjectFieldId: any;
    fastCreateEnterRecord: any;
    fieldType: any;
    boSourceType: any;
    createPlateformExtensionBusinessObjectField: any;
    oldComponentType: any;
    isEditMode: any;
    modal: any;
    domainId: any;
    updateBusinessObjectField: any;
    createBusinessObjectField: any;
    isFromDomain: any;
    dominFieldExtendsDs: any;
    templateCode: any;
    editDomainTemplateField: any;
    createDomainTemplateField: any;
    updatePlateformExtensionBusinessObjectField: any;
    createTenantExtensionBusinessObjectField: any;
    handleDeleteCheckApi: any;
    dispatchService: any;
    type: any;
}) => Promise<any>;
